server:
  port: 8888
spring: 
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bassball?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp